version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: crescendocrm-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: crescendocrm
      POSTGRES_PASSWORD: crescendocrm
      POSTGRES_DB: crescendocrm
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - crescendocrm

  # Redis for caching and queues
  redis:
    image: redis:7-alpine
    container_name: crescendocrm-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - crescendocrm

  # MinIO for S3-compatible object storage (development)
  minio:
    image: minio/minio:latest
    container_name: crescendocrm-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: crescendocrm
      MINIO_ROOT_PASSWORD: crescendocrm123
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - crescendocrm

  # Mailhog for email testing (development)
  mailhog:
    image: mailhog/mailhog:latest
    container_name: crescendocrm-mailhog
    restart: unless-stopped
    ports:
      - '1025:1025' # SMTP server
      - '8025:8025' # Web UI
    networks:
      - crescendocrm

  # pgAdmin for database management (development)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: crescendocrm-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@crescendocrm.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - crescendocrm
    depends_on:
      - postgres

  # Redis Commander for Redis management (development)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: crescendocrm-redis-commander
    restart: unless-stopped
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - '8081:8081'
    networks:
      - crescendocrm
    depends_on:
      - redis

volumes:
  postgres_data:
  redis_data:
  minio_data:
  pgadmin_data:

networks:
  crescendocrm:
    driver: bridge