packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  # React & Next.js
  react: ^18.2.0
  react-dom: ^18.2.0
  next: ^14.1.0

  # Node.js & NestJS
  '@nestjs/core': ^10.3.0
  '@nestjs/common': ^10.3.0
  '@nestjs/platform-express': ^10.3.0
  '@nestjs/config': ^3.2.0
  '@nestjs/jwt': ^10.2.0
  '@nestjs/passport': ^10.0.3
  '@nestjs/swagger': ^7.3.0
  '@nestjs/throttler': ^5.1.1

  # Database & ORM
  '@prisma/client': ^5.9.1
  'prisma': ^5.9.1
  'zod-prisma': ^0.5.4

  # Validation & Types
  zod: ^3.22.4
  '@types/node': ^20.11.17
  typescript: ^5.3.3

  # Authentication
  'next-auth': ^4.24.6
  'passport': ^0.7.0
  'passport-jwt': ^4.0.1
  'passport-google-oauth20': ^2.0.0

  # Queues & Caching
  'bull': ^4.12.2
  '@nestjs/bull': ^10.1.0
  'redis': ^4.6.13
  'ioredis': ^5.3.2

  # File Storage
  'aws-sdk': ^2.1543.0
  'multer': ^1.4.5-lts.1
  '@types/multer': ^1.4.11

  # Email
  '@sendgrid/mail': ^8.1.0
  'nodemailer': ^6.9.9

  # Payments
  'stripe': ^14.21.0

  # Utilities
  'date-fns': ^3.3.1
  'lodash': ^4.17.21
  'uuid': ^9.0.1
  'class-validator': ^0.14.1
  'class-transformer': ^0.5.1

  # Testing
  'jest': ^29.7.0
  '@testing-library/react': ^14.2.1
  '@testing-library/jest-dom': ^6.4.2
  'playwright': ^1.41.2
  'supertest': ^6.3.4

  # Linting & Formatting
  'eslint': ^8.56.0
  'prettier': ^3.2.5
  '@typescript-eslint/eslint-plugin': ^6.21.0
  '@typescript-eslint/parser': ^6.21.0

  # UI & Styling
  'tailwindcss': ^3.4.1
  '@headlessui/react': ^1.7.18
  '@heroicons/react': ^2.1.1
  'clsx': ^2.1.0
  'tailwind-merge': ^2.2.1

  # Monitoring
  '@opentelemetry/api': ^1.8.0
  '@opentelemetry/sdk-node': ^0.49.1
  '@opentelemetry/auto-instrumentations-node': ^0.42.0